#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
{{- if eq (include "eric-oss-eas-app-engineering.kafka-tls-enabled" .) "true" }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ include "eric-oss-eas-app-engineering.name" . }}-eric-data-message-bus-kf-int-cert
  labels:
  {{- include "eric-oss-eas-app-engineering.labels" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-eas-app-engineering.helm-annotations" .| nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-oss-eas-app-engineering.name" . }}-eric-data-message-bus-kf-secret
    certificateName: "cert.pem"
    privateKeyName: "key.pem"
  certificate:
    subject:
      cn: {{ include "eric-oss-eas-app-engineering.name" . }}
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: true
{{- end }}