apiVersion: v1
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJhcm1kb2NrZXIucm5kLmVyaWNzc29uLnNlIjogewogICAgICAgICAgICAidXNlcm5hbWUiOiAiY2xvdWRtYW4iLAogICAgICAgICAgICAicGFzc3dvcmQiOiAibWFuSW5UaGVDbG91ZHMyMDEzIiwKICAgICAgICAgICAgImF1dGgiOiAiWTJ4dmRXUnRZVzQ2YldGdVNXNVVhR1ZEYkc5MVpITXlNREV6IgogICAgICAgIH0sCiAgICAgICAgInNlbG5kb2NrZXIubW8uc3cuZXJpY3Nzb24uc2UiOiB7CiAgICAgICAgICAgICJ1c2VybmFtZSI6ICJjbG91ZG1hbiIsCiAgICAgICAgICAgICJwYXNzd29yZCI6ICJtYW5JblRoZUNsb3VkczIwMTMiLAogICAgICAgICAgICAiYXV0aCI6ICJZMnh2ZFdSdFlXNDZiV0Z1U1c1VWFHVkRiRzkxWkhNeU1ERXoiCiAgICAgICAgfSwKICAgICAgICAic2Vyb2RvY2tlci5zZXJvLmdpYy5lcmljc3Nvbi5zZSI6IHsKICAgICAgICAgICAgInVzZXJuYW1lIjogImNsb3VkbWFuIiwKICAgICAgICAgICAgInBhc3N3b3JkIjogIm1hbkluVGhlQ2xvdWRzMjAxMyIsCiAgICAgICAgICAgICJhdXRoIjogIlkyeHZkV1J0WVc0NmJXRnVTVzVVYUdWRGJHOTFaSE15TURFeiIKICAgICAgICB9CiAgICB9Cn0=
kind: Secret
metadata:
  name: k8s-registry-secret
type: kubernetes.io/dockerconfigjson
