kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: eric-eas-k6-pm-server-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-pm-server
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eric-oss-eas-app-engineering
        - podSelector:
            matchLabels:
              app: eas-k6