kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: eric-eas-k6-enmstub-policy-for-app-eng
spec:
  podSelector:
    matchLabels:
      app: eric-eo-enm-stub-for-app-eng
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: eas-k6
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eric-oss-eas-app-engineering
        - podSelector:
            matchLabels:
              app: eric-pm-server
        - podSelector:
            matchLabels:
              app: eric-eo-enm-adapter
