kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "eric-oss-eas-app-engineering.name" . }}-teh-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-oss-top-inv-exposure
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "eric-oss-eas-app-engineering.name" . }}
  policyTypes:
    - Ingress